# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

pod 'Brightcove-Player-Omniture'

target 'ADBMobileSamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ADBMobileSamples

end

target 'ADBMobileSamples - Bloodhound' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ADBMobileSamples - Bloodhound

end

target 'ADBMobileSamples - Dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ADBMobileSamples - Dev

end
